feat{create} create the site with html and css
AliMD/AliMDSchool-Homework pull request #5
Opened 2022-08-17 14:12 UTC by Amirmmolazemi

2022-08-17 15:04 UTC, A-sina commented on molazemi/my-first-website/index.html
> +<html lang="en">
add dir

2022-08-17 15:12 UTC, A-sina requested changes

2022-08-17 15:12 UTC, A-sina commented on molazemi/my-first-website/index.html
> +
better to remove spaces

2022-08-17 15:12 UTC, A-sina commented on molazemi/my-first-website/index.html
> +            <img class="avatar" src="../photo/myphoto.jpg">
width and height please

2022-08-17 15:12 UTC, A-sina commented on molazemi/my-first-website/index.html
> +                        <img src="../photo/image4.jpg" />
again width and height please

2022-08-17 15:12 UTC, A-sina commented on molazemi/my-first-website/index.html
> +                        <img src="../photo/image4.jpg" />
and add alt to your image tags

2022-08-17 15:12 UTC, A-sina commented on molazemi/my-first-website/index2.html
> +<html lang="en">
dir

2022-08-17 15:12 UTC, A-sina commented on molazemi/my-first-website/index2.html
> +            <img class="avatar" src="../photo/myphoto.jpg">
alt, width and height please

2022-08-17 15:12 UTC, A-sina commented on molazemi/my-first-website/index3.html
> +<html lang="en">
<!DOCTYPE html>

2022-08-17 15:14 UTC, A-sina commented on molazemi/my-first-website/index3.html
> +<html lang="en">
<!DOCTYPE html>

2022-08-17 15:26 UTC, A-sina commented on molazemi/my-first-website/style.css
> +}
ina dar 1 sotoon bashe moratab tare

2022-08-17 15:33 UTC, A-sina requested changes
thanks

2022-08-17 15:33 UTC, A-sina commented on molazemi/my-first-website/index3.html
> +<html lang="en">
DOCTYPE html and dir

2022-08-17 15:33 UTC, A-sina commented on molazemi/my-first-website/index3.html
> +
?

2022-08-17 15:33 UTC, A-sina commented on molazemi/my-first-website/index3.html
> +      <img class="photo" src="photo/myphoto.jpg" alt="my photo" />
width and height pls

2022-08-17 15:33 UTC, A-sina commented on molazemi/my-first-website/index3.html
> +      <br>
?

2022-08-17 15:33 UTC, A-sina commented on molazemi/my-first-website/index3.html
> +    <a href="https://instagram.com/amir341mohamad?igshid=YmMyMTA2M2Y=" alt="my instagram" target="_blank">
fix instagram link

2022-08-17 15:33 UTC, A-sina commented on molazemi/my-first-website/style2.css
> +     border-radius: 3px;
ye space ezafe dare ghablesh

2022-08-17 15:33 UTC, A-sina commented on molazemi/my-first-website/style2.css
> +     background-color: yellow;
ye space ezafe dare ghablesh

2022-08-17 15:33 UTC, A-sina commented on molazemi/my-first-website/style2.css
> +     background-color: #000;
ye space ezafe dare ghablesh

2022-08-17 15:33 UTC, A-sina commented on molazemi/my-first-website/style2.css
> +user-select: none;
tab

2022-08-17 16:42 UTC, Amirmmolazemi commented on molazemi/my-first-website/style2.css
> +user-select: none;
mamnoon babat goftan moshkelat ❤️ 
dorosteshoon kardam

2022-08-20 16:34 UTC, adltalab requested changes
found some issue in your codes, please check...

2022-08-20 16:34 UTC, adltalab commented on molazemi/my-first-website/index.html
> +                        <a class="nav-link" href="../index2.html">About me</a>
بهتره اسم فایلهای html متناسب با موضوعش انتخاب بشه...
به طور مثال:
about.html
contact.html
...

2022-08-20 16:34 UTC, adltalab commented on molazemi/my-first-website/index.html
> +                    <a class="social-link" href="https://instagram.com/amir341mohamad?igshid=YmMyMTA2M2Y=">
محتویات انتهای لینک اینستاگرام، نیاز نیست.
`https://instagram.com/amir341mohamad` کافیه

2022-08-20 16:34 UTC, adltalab commented on molazemi/my-first-website/index.html
> +                        <a class="nav-link" href="../index.html">Home</a>
why use  `../` !!

2022-08-21 00:35 UTC, adltalab requested changes

2022-08-21 00:35 UTC, adltalab commented on molazemi/my-first-website/style2.css
> +margin: 0%;
add tab

2022-08-22 12:35 UTC, Amirmmolazemi commented on molazemi/my-first-website/style2.css
> +margin: 0%;
tnx

2023-08-04 09:23 UTC, closed without merging